version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "80:80"
    volumes:
      - ./dic_frontend:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

